name: C2ME Build Script

on:
  push: {}
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 18
        java-package: jdk
        
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ./.gradle/loom-cache
        key: ${{ runner.os }}-gradle4-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle4-
        
    - name: Build C2ME
      run: |
        ./gradlew clean build --stacktrace

#    - name: Run FOSSA
#      uses: fossa-contrib/fossa-action@v1
#      with:
#        fossa-api-key: 46711dc8ef0a8d57d06010c8148bb6ea

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: c2me-artifact
        path: 'build/libs/*.jar'
      
